language: erlang
script: (rebar compile && rebar eunit skip_deps=true) || (find . -name "*.log" -print -exec cat \{\} \; && sh -c "exit 1")
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=99ba84bc061813790957ee348953cfb45e413900
  email: eng@basho.com
otp_release:
  - R15B01
  - R15B
  - R14B04
  - R14B03
