name: Erlang CI

on:
  push:
    branches: [ develop-3.0 ]
  pull_request:
    branches: [ develop-3.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.3]
      fail-fast: false
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do xref, dialyzer, eunit
